### PR TITLE
add xnaas.info

### PR DESCRIPTION
**Pull request by xnaas**
The HTML and CSS are ~1.86KB transferred (~2KB before compression), the massive favicon.ico
is the bulk of the site at 12.12KB transfered (32.21KB before compression).

### CODE REVIEW

**Comment by xnaas** [comment]
I took an alternative approach to the favicon and it's now only 2.03KB.

**Comment by boehs** [comment]
How did you reduce the favicon? my 32x32 is clocking in at a massive 3.4 kB!

**Comment by xnaas** [comment]
@boehs: I talked about my process [a little bit here](https://tildes.net/~comp/zff/the_250kb_club#comment-6ycp) on [tildes.net](https://tildes.net/).

**Comment by nkoehring** [comment]
Awesome! I love to see that there is even some conversation about the page sizes happening!
Welcome to the 250kb Club!

**Comment by xnaas** [comment]
> Welcome to the 250kb Club!

Thanks! Next up: a 25kb club and a 5kb club and an elitist 1kb and/or 0kb club! 😜 

> Awesome! I love to see that there is even some conversation about the page sizes happening!

Wait until you see people sick of the web entirely who are all circlejerking each other on [Gemini](https://gemini.circumlunar.space/). 😉

**Pull request merged**
